Corte de Caja Backend
Bitquark-Software/acqua-lavanderias pull request #106
Opened 2024-03-26 05:13 UTC by ElianLvX

# Corte de Caja

 - [x] Cree la tabla corte_caja es donde se llevara acabo la apertura y cierre de las cajas por sucursal para abrir la caja se hace uso de un código administrador esta tabla tiene también el CRUD.
- [x] Middlewares
        - VerificarCajaAbiertaMiddleware.php: este es para bloquear las rutas si no existe una caja abierta para la sucursal del usuario 
                                                                     logueado
        - FlexCajaAdminMiddleware: sirve para darle acceso al administrador a casi todo excepto resivir pagos X de cualquier ticket
- [x] Agregue el corte de caja a los modelos con los que esta relacionado.
- [x] Ajuste algunas cosas de anticipos_tickets como no permitir hacer pagos desde otra sucursal, permitira el pago si y solo si el ticket pertenece a la sucursal del usuario actualmente logueado.
- [x] Ajuste el Seeder de Sucursales para que no de error al migrar. es mas para el entorno de desarrollo que daba el error cuando hacia un refresh a la BD.
- [x] ajuste algunas cosas en la creacion de los codigos de administrador se le puede pasar directamente el ticket que se quiere eliminar(cancelar) y automáticamente ese codigo ya no se usara.

Como tal este seria el bloque para el funcionamiento para administración de las cajas:

```
Route::middleware('auth:api', 'role:administrador,encargado,cajero')->group(function () {
        // Ganancias efectivo,transferencia y tarjeta por sucursal
       Route::post('gestion-caja-ganancias', [CorteCajaController::class, 'ventaGeneral'])->name('gestion-caja-ganancias');
       Route::middleware('role:administrador,encargado')->group(function () {
        // Generacion de Codigos de Cancelacion Tickets
        Route::apiResource('codigos-admin', CodigoAdminController::class);
        // Buscador de Codigos
        Route::post('busqueda_codigo', [CodigoAdminController::class, 'buscarCodigo'])->name('codigos.buscar');
        // Aperturas y Cortes de cajas
        Route::apiResource('gestion-caja', CorteCajaController::class);
    });
});
```

tratare de hacer algunas de las rutas en swagger para que se entienda un poco mejor el funcionamiento.

2024-03-28 15:08 UTC, its-dev-fer requested changes
Cambios menores en http status

2024-03-28 15:08 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/AnticiposTicketsController.php
> +            ]);
http status 400

2024-03-28 15:08 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +                    'mensaje' => 'ticket para cancelacion no encontrado'
http 404

2024-03-28 15:08 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +        $mensajePersonalizadoAdmin = $fecha_actual ? 'Ticket eliminado correctamente, codigoadmin usado correctamente' :
Ticket eliminado? No sería codigo admin eliminado?

2024-03-28 15:08 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CorteCajaController.php
> +                ]);
http 400

2024-03-28 15:08 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CorteCajaController.php
> +            ], 403);
404

2024-03-29 07:08 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +        $mensajePersonalizadoAdmin = $fecha_actual ? 'Ticket eliminado correctamente, codigoadmin usado correctamente' :
Cuando se crea solo el codigo admin muestra el mensaje de 'Codigo administrador generado exitosamente' pero si el codigo es para cancelar un ticket se muestra 'Ticket eliminado correctamente, codigoadmin usado correctamente' esto depende si se pasa el id_ticket en el request

2024-03-29 15:50 UTC, its-dev-fer approved these changes

2024-03-29 15:50 UTC, merged