Feat/AL-41-Frontend-Generador-Codigos-Admin
Bitquark-Software/acqua-lavanderias pull request #107
Opened 2024-03-31 21:57 UTC by Rodrigo-Hip27989

Frontend Generador de Códigos

2024-04-02 23:49 UTC, its-dev-fer requested changes
Cambios menores, favor de ejecutar `npm version patch`

2024-04-02 23:49 UTC, its-dev-fer commented on acqua-frontend/src/app/components/admin-codes/admin-codes.component.html
> +            Actualizar Estado Del Código Actual
Este es el que espera el ticket id, verdad? Para que se oculte por el momento

2024-04-02 23:49 UTC, its-dev-fer commented on acqua-frontend/src/app/components/drawer/drawer.component.html
> +          Codigos Admin
Códigos de administrador

2024-04-03 03:37 UTC, Rodrigo-Hip27989 commented on acqua-frontend/src/app/components/admin-codes/admin-codes.component.html
> +            Actualizar Estado Del Código Actual
Si, ya está oculto con el ngIf

2024-04-03 03:39 UTC, Rodrigo-Hip27989 commented on acqua-frontend/src/app/components/drawer/drawer.component.html
> +          Codigos Admin
Ok

2024-04-05 04:07 UTC, its-dev-fer approved these changes

2024-04-05 04:07 UTC, merged