Agrega controlador de autenticación y migración de usuarios
Bitquark-Software/acqua-lavanderias pull request #27
Opened 2023-06-19 18:19 UTC by ElianLvX

### Autenticación y migración (Rol)

- [x] Creacion de migracion para rol.
- [x] Rutas con Passport.
- [x] Controlador AuthController.
- [x]  Modificación de AuthServiceProvider para Passport
Y tambien se modificaron otros para el funcionamiento de passport

2023-06-19 19:10 UTC, its-dev-fer requested changes
Resuelve los conflictos con __*rebase*__, no uses merge.

2023-06-19 19:10 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/AuthController.php
> +            $accessToken = $user->createToken('example')->accessToken;
```php
$accessToken = $user->createToken('login-token')->accessToken;
```

2023-06-19 19:10 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/AuthController.php
> +            ], 200);
```php
return new Response([
                'access_token' => $accessToken,
                'datos' => $userData,
                'permisos' => $user->role,
], 200);
```

2023-06-19 19:15 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/AuthController.php
> +            ], 200);
en este caso userData ya llevaria el rol incluido en la respuesta
digo para no volver a poner el 'permisos' => $user->role

2023-06-19 23:52 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/AuthController.php
> +            ], 200);
Me parece perfecto, para que no lleve el atributo `mensaje`

2023-06-20 03:20 UTC, its-dev-fer approved these changes

2023-06-20 03:21 UTC, merged