Middleware de Administrador y Creación de Columna Role
Bitquark-Software/acqua-lavanderias pull request #28
Opened 2023-06-21 17:31 UTC by ElianLvX

Uní las rama de AL-1 AL-1-BACKEND-AUTH con la rama actual en el repositorio local
debido a que necesitaba implementar de nuevo el passpor(tokens) debido a que la ruta con el middleware pide el token de inicio de sesión para hacer las pruebas elimine algunos archivos para evitar conflictos.

- [x] Creación de MiddleWare para Administrador
- [x] Creación de Controlador (UserController) para dar de Alta a administrador y Empleados
- [x] Creacion de un seeder para hacer las pruebas de Inicio de Sesion (Un Empleado, Un Cliente) 
- [x] Creacion de Columna Role

2023-06-22 19:01 UTC, its-dev-fer requested changes

2023-06-22 19:01 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CatalogoController.php
> +        return response()->json(['messaje' => 'Catalogo Actualizado...'], 200);
typo: `messaje` -> `mensaje`

2023-06-22 20:15 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/CatalogoController.php
> +        return response()->json(['messaje' => 'Catalogo Actualizado...'], 200);
solo se le cambiaria de message a mensaje? si es así solo en esa respuesta?

2023-06-22 22:21 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CatalogoController.php
> +        return response()->json(['messaje' => 'Catalogo Actualizado...'], 200);
Así es, solo sería eso. Lo demás está excelente

2023-06-23 18:47 UTC, its-dev-fer approved these changes

2023-06-23 18:47 UTC, merged