CRUD de Clientes y Direcciones
Bitquark-Software/acqua-lavanderias pull request #30
Opened 2023-06-24 02:51 UTC by ElianLvX

# Tareas Realizadas
## Creación de Modelos

- [x] Cliente
- [x] Dirección 

## Creación de Controladores

- [x] ClienteController
- [x] DirecciónController

Y también se crearon las Migraciones de cada uno de estos.

En las Funciones Destroy

- [x] Se restringió a que solo el administrador pueda eliminar
se utiliza la autenticación basada en Tokens de API el token que da al hacer Login

2023-06-24 03:28 UTC, its-dev-fer requested changes
Cambios menores en el sanitizado de los inputs, falta un endpoint para buscar a un cliente por nombre o número de teléfono. Una disculpa por no dar el requerimiento completo.

2023-06-24 03:28 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/ClienteController.php
> +        $cliente = Cliente::create([
Usa los helpers Str::title()

2023-06-24 03:28 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/ClienteController.php
> +            'nombre' => $request->nombre,
Igual, Str::title()

2023-06-24 03:28 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/DireccionController.php
> +            'calle' => $request->calle,
Aquí todos llevarán el helper Str::upper()

2023-06-24 03:57 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/ClienteController.php
> +        $cliente = Cliente::create([
Inge Disculpe lo crearía en otro controlador o implemento las funciones dentro del controlador de Clientes?

2023-06-24 04:30 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/ClienteController.php
> +        $cliente = Cliente::create([
en cuales se utilizaría este helper Str::title() ? solo en nombre ing?

2023-06-24 17:39 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/ClienteController.php
> +        $cliente = Cliente::create([
En el mismo controlador, irían los helpers Str en nombre

2023-06-24 17:40 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/ClienteController.php
> +        $cliente = Cliente::create([
Y en la dirección irían todos en mayúscula en todos los apartados menos código postal y cliente id

2023-06-24 19:43 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/ClienteController.php
> +        $cliente = Cliente::create([
inge en uste caso la url quedaria asi: api/clientes/nombre/{nombre}   , no se si seria mejor tratar el nombre como URL es decir dejarlo por ejemplo asi api/clientes/nombre/eliàn-lòpez-villa digo para que tenga consistencia, si es asi se tendria que usar el Helper Str:slug que convierte espacios en "-" y quita los acentos y al momento de buscar utilizaria esto: str_replace(' ', '-', $nombre); para cambiar los empascios de los nombres que se busquen y asi buscarlos en la BD no se como vea.

2023-06-26 01:00 UTC, its-dev-fer approved these changes

2023-06-26 04:12 UTC, merged