Middleware para Autenticar y responder con Json y Correccion de rutas
Bitquark-Software/acqua-lavanderias pull request #31
Opened 2023-06-27 04:44 UTC by ElianLvX

- [x] Creación de Middleware para verificar autenticacion por medio de token
- [x] Corrección de Rutas en archivo api.php

2023-06-28 04:22 UTC, its-dev-fer requested changes
Cambios en api.php

2023-06-28 04:22 UTC, its-dev-fer commented on acqua-backend/routes/api.php
> +});
Cambia a:

```php
Route::middleware(['auth:api', CheckAuthResponseMiddleware::class, AdminOnlyMiddleware::class])->group(function () {
    Route::apiResource('catalogos', CatalogoController::class)->except('index', 'show'); // CRUD CATALOGOS
    Route::apiResource('servicios', ServiciosController::class)->except('index', 'show'); // CRUD SERVICIOS
});
```

2023-06-28 04:41 UTC, ElianLvX commented on acqua-backend/routes/api.php
> +});
ya edite esa parte ing, ya esta arriba el commit de este PR

2023-06-28 06:17 UTC, its-dev-fer commented on acqua-backend/routes/api.php
> +});
Que raro, me aparece igual

2023-06-28 06:20 UTC, its-dev-fer commented on acqua-backend/routes/api.php
> +});
Cambiar a:

```php
Route::middleware(['auth:api', CheckAuthResponseMiddleware::class, CheckAuthResponseMiddleware::class, AdminOnlyMiddleware::class])->group(function () {
    Route::apiResource('catalogos', CatalogoController::class)->except('index', 'show'); // CRUD CATALOGOS
    Route::apiResource('servicios', ServiciosController::class)->except('index', 'show'); // CRUD SERVICIOS
});
```

2023-06-28 06:20 UTC, its-dev-fer commented on acqua-backend/routes/api.php
>  Route::apiResource('clientes', ClienteController::class); // CRUD CLIENTE
Eliminar

2023-06-28 06:22 UTC, its-dev-fer requested changes
Comentarios line a linea

2023-06-28 06:41 UTC, ElianLvX commented on acqua-backend/routes/api.php
>  Route::apiResource('clientes', ClienteController::class); // CRUD CLIENTE
Elimino la ruta? o lo pongo en la misma linea?

2023-06-28 06:43 UTC, ElianLvX commented on acqua-backend/routes/api.php
>  Route::apiResource('clientes', ClienteController::class); // CRUD CLIENTE
si lo pongo todo en una linea no me deja hacer el commit ing

2023-06-29 03:48 UTC, its-dev-fer approved these changes

2023-06-29 03:49 UTC, merged