Tabla Tickets y Algunos Ajustes
Bitquark-Software/acqua-lavanderias pull request #39
Opened 2023-07-28 04:57 UTC by ElianLvX

# Tabla de Tickets

- [x] Migración.
- [x] Modelo .
- [x] Controlador
- [x] Ruta (api.php) creada
- [x] Asignación de Middleware de "Auth:api" para Autenticación
- [x] Asignación de Middleware de "AdminOnlyMiddleware"
	- [x] Solo los Empleados pueden acceso a Index, Store, Show
	- [x] y los administradores a todo el CRUD

- [x]  En Cliente, Comentario, Dirección, Sucursal se agregaron las relaciones inversas con Ticket
_ __
## Ajustes a tabla Comentarios
- [x] Corregí algunos detalles del controlador y algunos errores en la parte de la validación

2023-07-28 21:12 UTC, its-dev-fer requested changes
Cambios de los comentarios, rebase con develop para actualizar los refs de la rama

2023-07-28 21:12 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/TicketController.php
> +        return Ticket::paginate(15);
Puedes poner un sortBy('createdAt', 'DESC') para que se ordenen de los más recientes a los más viejos.

2023-07-28 21:12 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/TicketController.php
> +            'envio_domicilio' => ['boolean'],
con solo poner boolean pasa la validación de required?

2023-07-28 21:12 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/TicketController.php
> +            'status' => ['required', 'in:LAVADO,PLANCHADO,RECONTEO,ENTREGA']
Perdón, agrega un estado inicial `CREADO`, para que todos los tickets tengan ese valor por defecto

2023-07-28 21:12 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/TicketController.php
> +            'status' => $request->status
por defecto tendrá el status de `CREADO`, no dependerá de la solicitud del cliente

2023-07-28 21:12 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/TicketController.php
> +            'anticipo' => $request->anticipo,
```php
'anticipo' => $request->tipo_credito === 'CREDITO' ? $request->anticipo : 0,
```

Si el cliente manda un dato erróneo como anticipo cuando la compra sea de contado se producirá este error

2023-07-28 21:12 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/TicketController.php
> +            'restante' => round($restante, 2),
```php
'restante' => $request->tipo_credito === 'CREDITO' ? ($request->total - $request->anticipo) : 0,
```
No entendí porqué se usa `round()` si el restante puede ser un decimal

2023-07-28 21:12 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/TicketController.php
> +            'restante' => round($restante, 2),
Igual que el comentario anterior, calcula el restante y anticipo siempre y cuando el tipo de compra sea por crédito

2023-07-28 21:12 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/TicketController.php
> +            'restante' => round($restante, 2),
TODO: Agregar un campo para un soft delete, algo así como `vencido` con un valor falso por defecto y true si se desea cancelar

2023-07-28 21:12 UTC, its-dev-fer commented on acqua-backend/app/Models/Ticket.php
> +        'status'
TODO: Columna nueva que indique un softt delete llamado `vencido`

2023-07-28 21:12 UTC, its-dev-fer commented on acqua-backend/database/migrations/2023_07_18_075649_create_tickets_table.php
> +
TODO: Columna nueva que indique un softt delete llamado `vencido`, por defecto será false, solo puede ser de tipo booleano.

2023-07-29 04:14 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/TicketController.php
> +            'envio_domicilio' => ['boolean'],
Si de hecho en la migración ya tiene asignado por default True como anteriormente me había comentado a menos de que se le pase un false cambia ing

2023-07-29 06:54 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/TicketController.php
> +        return Ticket::paginate(15);
que le parece esta busque en Eloquent y encontré orderBy, ordenándome los tickets mas recientes en orden descendente y después aplico la paginación

`Ticket::orderBy('created_at', 'desc')->paginate(15);`

2023-07-31 07:21 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/TicketController.php
> +            'restante' => round($restante, 2),
ing como tal el atributo vencido lo pasaría tanto el el create como en el update no?
es decir que cuando cree el ticket pueda asignar también un true en vencido?

2023-07-31 19:16 UTC, its-dev-fer approved these changes

2023-07-31 19:16 UTC, merged