Tabla Procesos Ticket
Bitquark-Software/acqua-lavanderias pull request #45
Opened 2023-08-06 23:47 UTC by ElianLvX

# Tabla Procesos Ticket

- [x] Migración.
- [x] Modelo .
- [x] Controlador
- [x] Ruta (api.php) creada (Index, Store, Show). Con AuthMiddleware
- [x] Relaciones Inversas agregadas en los modelos: Lavadora, Proceso, User
faltaría la relación inversa de sacadoras que lo agregare en el PR de Secadoras que sigue abierto con un commit.

2023-08-09 23:52 UTC, its-dev-fer requested changes
El comentario y el rebase

2023-08-09 23:52 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/ProcesoTicketController.php
> +    }
Falta el update para ProcesoTicket ya que se debe actualizar el timestamp_end

2023-08-10 05:52 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/ProcesoTicketController.php
> +    }
Ya esta listo ING! de paso agregue la relación inversa de secadoras en el modelo de secadoras.

2023-08-15 23:49 UTC, its-dev-fer approved these changes

2023-08-15 23:49 UTC, merged