Fix/frontend dashboard
Bitquark-Software/acqua-lavanderias pull request #83
Opened 2024-01-09 10:38 UTC by Rodrigo-Hip27989

* Se refactorizo el componente ticket-preview
* Se agrego el soporte para guardar el dato 'total_iva' en la tabla tickets de la base de datos

2024-01-10 18:09 UTC, its-dev-fer requested changes

2024-01-10 18:09 UTC, its-dev-fer commented on acqua-frontend/src/app/components/tickets/ticket-preview/ticket-preview.component.ts
> +    console.log('Saldo pendiente');
remueve esta linea por favor

2024-01-11 23:24 UTC, Rodrigo-Hip27989 commented on acqua-frontend/src/app/components/tickets/ticket-preview/ticket-preview.component.ts
> +    console.log('Saldo pendiente');
Ya quedo

2024-01-16 00:47 UTC, its-dev-fer approved these changes

2024-01-16 00:48 UTC, its-dev-fer approved these changes

2024-01-16 00:48 UTC, merged