Feat/lavadora secadora adicional
Bitquark-Software/acqua-lavanderias pull request #88
Opened 2024-01-30 00:28 UTC by Rodrigo-Hip27989

- Se agrego la funcionalidad para agregar una lavadora/secadora extra en los procesos del ticket

2024-01-30 02:24 UTC, its-dev-fer requested changes

2024-01-30 02:24 UTC, its-dev-fer commented on acqua-frontend/package-lock.json
> -  "lockfileVersion": 1,
Por qué el cambio de lockfileVersion?

2024-01-30 02:24 UTC, its-dev-fer commented on acqua-frontend/src/app/components/tickets/detalles-ticket/detalles-ticket.component.html
> +        <br><p>* Seleccionar una lavadora extra para separar las ropas blancas de las ropas de color</p><br>
cambia "Seleccionar una lavadora extra para separar las ropas blancas de las ropas de color" por "Seleccionar una lavadora extra en caso de que el servicio ocupe más de una"

2024-01-30 02:24 UTC, its-dev-fer commented on acqua-frontend/src/app/components/tickets/detalles-ticket/detalles-ticket.component.html
> +        <br><p>* Seleccionar una secadora extra para separar roblas blancas de las ropas de color</p><br>
Cambia por "Selecciona una secadora extra en caso de que el servicio ocupe más de una"

2024-01-30 02:24 UTC, its-dev-fer commented on acqua-frontend/src/app/components/tickets/detalles-ticket/detalles-ticket.component.ts
> +      const procesos_de_lavado: ProcesoTicket[] = this.getTicketProcessesById(3);
este ID 3 es fijo?

2024-01-30 02:24 UTC, its-dev-fer commented on acqua-frontend/src/app/components/tickets/detalles-ticket/detalles-ticket.component.ts
> +      const procesos_de_secado: ProcesoTicket[] = this.getTicketProcessesById(4);
No uses ID's fijos, si es posible pidele a Elian que te cree un nuevo endpoint para que obtengas el ID correcto desde ahí.

2024-01-30 02:24 UTC, its-dev-fer commented on acqua-frontend/src/app/components/tickets/detalles-ticket/detalles-ticket.component.ts
> +      const procesos_de_secado: ProcesoTicket[] = this.getTicketProcessesById(4);
Algo así como:
```ts
const listadoProcesos = this.ticketService.getIDListadoProcesos('lavado');
```

2024-01-30 02:24 UTC, its-dev-fer commented on acqua-frontend/src/app/components/tickets/detalles-ticket/detalles-ticket.component.ts
> +      const procesos_de_secado: ProcesoTicket[] = this.getTicketProcessesById(4);
Creo que `PROCESOS_EXISTENTES` maneja el nombre y el ID.

2024-01-30 02:24 UTC, its-dev-fer commented on acqua-frontend/src/app/components/tickets/detalles-ticket/detalles-ticket.component.ts
> +    return !this.noExisteProcesoExtras(4);
Igual, reemplaza los ID´s por los variables en lugar de usar un número fijo.

2024-01-30 02:24 UTC, its-dev-fer commented on acqua-frontend/src/app/dtos/proceso.ts
> +export class ResDatLavSecXtra
Mejora el nombre de la clase a: ResponseDataLavadoraSecadoraExtra, es largo pero es mas legible

2024-01-30 02:24 UTC, its-dev-fer commented on acqua-frontend/src/app/dtos/proceso.ts
> +export class ResLavSecXtra
Mejora el nombre de la clase a: ResponseLavadoraSecadoraExtra, es largo pero es mas legible

2024-01-30 04:16 UTC, Rodrigo-Hip27989 commented on acqua-frontend/package-lock.json
> -  "lockfileVersion": 1,
Creo que ocurrió al compilarlo

2024-01-30 04:17 UTC, Rodrigo-Hip27989 commented
![Proceso lavado - 01](https://github.com/Bitquark-Software/acqua-lavanderias/assets/77178732/8e933f21-df32-4671-9f8a-07aa3ed9d060)
![Proceso lavado - 02](https://github.com/Bitquark-Software/acqua-lavanderias/assets/77178732/7d5da088-9df4-4d15-95bf-549cb5d7b724)
![Proceso secado - 01](https://github.com/Bitquark-Software/acqua-lavanderias/assets/77178732/1a09f657-54aa-4436-b88b-a54d978c9338)
![Proceso secado - 02](https://github.com/Bitquark-Software/acqua-lavanderias/assets/77178732/05f65d0e-0c79-42bd-85c4-195df4d3c79b)

2024-01-30 04:19 UTC, Rodrigo-Hip27989 commented on acqua-frontend/src/app/components/tickets/detalles-ticket/detalles-ticket.component.ts
> +      const procesos_de_lavado: ProcesoTicket[] = this.getTicketProcessesById(3);
Si

2024-01-30 04:21 UTC, Rodrigo-Hip27989 commented on acqua-frontend/src/app/components/tickets/detalles-ticket/detalles-ticket.component.ts
> +      const procesos_de_secado: ProcesoTicket[] = this.getTicketProcessesById(4);
Esta bien

2024-01-30 05:27 UTC, its-dev-fer commented on acqua-frontend/package-lock.json
> -  "lockfileVersion": 1,
Porfa, descarta los cambios de ese archivo si es necesario, debería aumentar la versión con npm version patch

2024-01-30 05:28 UTC, its-dev-fer commented on acqua-frontend/src/app/components/tickets/detalles-ticket/detalles-ticket.component.ts
> +      const procesos_de_secado: ProcesoTicket[] = this.getTicketProcessesById(4);
Porfa, todos aquellos lugares donde usas los ID´s fijos deben de ser con esa función nueva para tener el ID en automático en dado caso que llegaran a cambiar

2024-02-01 22:44 UTC, its-dev-fer approved these changes

2024-02-06 17:54 UTC, its-dev-fer approved these changes

2024-02-08 22:08 UTC, merged