Fix/frontend user request
Bitquark-Software/acqua-lavanderias pull request #94
Opened 2024-02-22 04:58 UTC by Rodrigo-Hip27989

- AL-17: Se agrego la redirección a los datos del cliente para agregar una dirección
- AL-18: Se cambio la palabra Kilos a Cantidad en el modal de ver servicios
- AL-19: Se cambio el color del icono de los tickets entregados - pagados y listos para entregar
- AL-20: Se redondeo el cambio con la condición de 0.41 > 0.5
- AL-21: Al registrar un monto fraccionario ya permite continuar con la operación
- AL-22: Los imputs de kilos ya permite agregar una cantidad superior al minimo especificado
- AL-23: Se agrego la fecha y la hora en la impresión del ticket
- AL-24: Se agregaron los campos para seleccionar una hora y minuto de entrega

2024-02-22 20:24 UTC, its-dev-fer requested changes

2024-02-22 20:24 UTC, its-dev-fer commented on acqua-frontend/src/app/components/caja/caja.component.html
> +          <button class="btn btn-xs btn-success join-item" (click)="saveTicket()" [disabled]="((incluir_iva == true) && (total_iva == 0))">Finalizar venta</button>
Buena observación

2024-02-22 20:24 UTC, its-dev-fer commented on acqua-frontend/src/app/components/tickets/detalles-ticket/detalles-ticket.component.html
> +          [routerLink]="['/editar-cliente', ticket.id_cliente]"
Al darle click directamente lo lleva a agregar una dirección independientemente de que ya tenga una?

2024-02-22 20:25 UTC, its-dev-fer commented
Faltó ejecutar `npm version patch` para que sea la actualización 1.1.4

2024-02-22 23:42 UTC, Rodrigo-Hip27989 commented on acqua-frontend/src/app/components/tickets/detalles-ticket/detalles-ticket.component.html
> +          [routerLink]="['/editar-cliente', ticket.id_cliente]"
Ya vi el problema

2024-02-22 23:42 UTC, Rodrigo-Hip27989 commented on acqua-frontend/src/app/components/tickets/detalles-ticket/detalles-ticket.component.html
> +          [routerLink]="['/editar-cliente', ticket.id_cliente]"
Lo voy a cambiar

2024-02-25 17:00 UTC, its-dev-fer requested changes

2024-02-25 17:00 UTC, its-dev-fer commented on acqua-frontend/src/app/components/tickets/tickets.component.html
> +                      'bg-indigo-600': +ticket.restante! > 0,
Aquí, si el ticket tiene un restante 0 no quiere decir que ya está entregado por completo, falta validar que el ticket tenga en su lista de procesos el proceso de `ENTREGA` y además, tenga tanto `timestamp_start` y `timestamp_end`, si la condición se cumple se aplica el fondo `bg-indigo-600`, si no, el `btn-success`

2024-02-25 21:40 UTC, Rodrigo-Hip27989 commented on acqua-frontend/src/app/components/tickets/tickets.component.html
> +                      'bg-indigo-600': +ticket.restante! > 0,
Esta bien, lo voy a corregir.

2024-02-25 21:49 UTC, Rodrigo-Hip27989 commented on acqua-frontend/src/app/components/tickets/tickets.component.html
> +                      'bg-indigo-600': +ticket.restante! > 0,
Entonces el `bg-indigo-600` es el completado y `btn-success` para el que no

2024-02-26 02:54 UTC, Rodrigo-Hip27989 commented on acqua-frontend/src/app/components/tickets/tickets.component.html
> +                      'bg-indigo-600': +ticket.restante! > 0,
No me queda esta parte

2024-02-26 18:46 UTC, its-dev-fer commented on acqua-frontend/src/app/components/tickets/tickets.component.html
> +                      'bg-indigo-600': +ticket.restante! > 0,
Tiene sentido lo que dices, indigo que se use para cuando aún no se ha contemplado y el btn-sucess cuando ya se haya completa con sus validaciones correspondientes. Una disculpa por la confusión.

2024-02-26 23:18 UTC, Rodrigo-Hip27989 commented on acqua-frontend/src/app/components/tickets/tickets.component.html
> +                      'bg-indigo-600': +ticket.restante! > 0,
No hay de que. Solo que me refería a las validaciones del timestamp las que no me quedan

2024-02-26 23:43 UTC, its-dev-fer commented on acqua-frontend/src/app/components/tickets/tickets.component.html
> +                      'bg-indigo-600': +ticket.restante! > 0,
Si ocupas ayuda me dices para entrar en sesión y revisarlo

2024-02-27 23:12 UTC, its-dev-fer approved these changes

2024-02-27 23:12 UTC, merged