EndPoint Creación de Codigos
Bitquark-Software/acqua-lavanderias pull request #96
Opened 2024-03-02 20:19 UTC by ElianLvX

# Endpoint Cancelación por Código

- [x] Creación de Migración **2024_02_28_180450_create_cancelacion_codigos_table.php** para almacenar códigos creados.
- [x] Creación de Controlador **CancelacionCodigoController.php**.
- [x] Creación de Modelo **CancelacionCodigo.php**
- [x] Ajustes al método destroy de TicketsController.php para pedir un código para cancelar el ticket.
- [x]  Creacion de la rutas 
         1. cancelacion_codigo ->   index,store, show y update para creación de códigos
         2. busqueda_codigo    ->   buscador de codigos

2024-03-05 02:26 UTC, its-dev-fer requested changes

2024-03-05 02:26 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +            $codigoGenerado = Str::random(8);
El código debe ser con la siguiente estructura `ABCD0123`

2024-03-05 02:26 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +        } while (CodigoAdmin::where('codigo', $codigoGenerado)->exists());
La condición va a generar un código mientras `exista un código generado` igual? O sería mientras `no exista`?

2024-03-05 02:26 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +            $codigoGenerado = Str::random(8);
Las letras deberán ser en mayúsculas

2024-03-05 02:26 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +        $codigo = CodigoAdmin::where('codigo', $request->codigo)
Considerar que las letras serán mayúsculas

2024-03-05 02:26 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +            ], 201);
201 es para un elemento creado, en este caso 200 está bien

2024-03-05 02:26 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +        $verificacionUsadoCodigo = CodigoAdmin::where('usado', '=', 0)->exists();
Falta la condición del id de usuario generado

2024-03-05 02:26 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +            'codigo' => $codigoGenerado,
Considerar las mayúsculas

2024-03-05 02:26 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +            'motivo' => $request->motivo,
Para tener datos sanitizados será buena idea usar Str::upper()

2024-03-05 02:26 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +    public function update(Request $request, CodigoAdmin $cancelacionCodigo)
Duda, al pasar una variable de tipo `CodigoAdmin` espera el objeto completo o espera un ID?

2024-03-05 02:26 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +                    'mensaje' => 'Codigo de Cancelacion usado o Vinculado a un ticket'
http status 422

2024-03-05 02:26 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/TicketController.php
> +            $ticket->comentarios()->delete();
No causará conflicto con otras relaciones?

2024-03-05 02:26 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/TicketController.php
> +            ], 404);
403

2024-03-05 02:26 UTC, its-dev-fer commented on acqua-backend/routes/api.php
> +    Route::apiResource('codiogos-admin', CodigoAdminController::class);
typo: `codiogos` -> `codigos`

2024-03-05 03:34 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +            $codigoGenerado = Str::random(8);
Ah perfecto editare ese bloque

2024-03-05 03:34 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +        } while (CodigoAdmin::where('codigo', $codigoGenerado)->exists());
eh como tal la consulta busca un código parecido al que se acaba de generar el exists() me retorna un bool que si es true es que existe un código igual al que se acaba de generar y vuelve a iterar para que genere otro.

2024-03-05 03:35 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +        $verificacionUsadoCodigo = CodigoAdmin::where('usado', '=', 0)->exists();
esta parte no la entiendo bien ing

2024-03-05 03:38 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +    public function update(Request $request, CodigoAdmin $cancelacionCodigo)
esa parte si se me fue, solo es necesario le $id, voy a corregirlo

2024-03-05 03:39 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/TicketController.php
> +            $ticket->comentarios()->delete();
esa linea estaba antes de crear el softdelete a tickets en un momento la quito ya que no es necesaria.

2024-03-06 23:28 UTC, its-dev-fer requested changes

2024-03-06 23:28 UTC, its-dev-fer commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +        $fecha_actual = date("Y-m-d H:i:s");
por qué se cambia de d-m-Y a Y-m-d?

2024-03-08 04:41 UTC, ElianLvX commented on acqua-backend/app/Http/Controllers/CodigoAdminController.php
> +        $fecha_actual = date("Y-m-d H:i:s");
a es que esa fecha no la acepta la BD como tal la estructura el timestamp solo acepta 
Año-Mes-Dia Hora-Minuto-Segundo     así debería de ser

2024-03-12 16:53 UTC, its-dev-fer commented
Rebase y con eso queda

2024-03-15 01:17 UTC, its-dev-fer approved these changes

2024-03-15 01:18 UTC, merged